name: Pull Request

on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, reopened, synchronize]

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Copy .env && Generate App Keys
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Install NPM Dependencies
        run: npm install

      - name: Execute tests (Unit and Feature tests) using PHPUnit
        run: vendor/bin/phpunit --verbose
